import { v4 as uuid } from "uuid";
import prod1 from "../../assets/card-images/prod1.jpeg";
import prod2 from "../../assets/card-images/prod2.jpeg";
import prod3 from "../../assets/card-images/prod3.jpeg";
import prod4 from "../../assets/card-images/prod4.jpeg";
import prod5 from "../../assets/card-images/prod5.jpeg";
import prod16 from "../../assets/card-images/prod16.jpeg";
import prod7 from "../../assets/card-images/prod7.jpeg";
import prod8 from "../../assets/card-images/prod8.jpeg";
import prod9 from "../../assets/card-images/prod9.jpeg";
import prod10 from "../../assets/card-images/prod10.jpeg";
import prod11 from "../../assets/card-images/prod11.jpeg";
import prod12 from "../../assets/card-images/prod12.jpeg";
import prod13 from "../../assets/card-images/prod13.jpeg";
import prod14 from "../../assets/card-images/prod14.jpeg";
import prod15 from "../../assets/card-images/prod15.jpeg";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: "p1",
    brand: "Suzuki",
    model: "Wagon R",
    price: "50000",
    categoryName: "hatchback",
    fueltype: "Petrol",
    releaseYear: 2000,
    mileage: 20,
    preowned: false,
    ncap: 1.7,
    url: prod1,
  },
  {
    _id: "p2",
    brand: "Suzuki",
    model: "Swift Dzire",
    price: "700000",
    categoryName: "sedan",
    fueltype: "Diesel",
    releaseYear: 2001,
    mileage: 22,
    preowned: false,
    ncap: 3.0,
    url: prod2,
  },
  {
    _id: "p3",
    brand: "Tata",
    model: "Nexon",
    price: "900000",
    categoryName: "suv",
    fueltype: "Diesel",
    releaseYear: 2015,
    mileage: 20,
    preowned: false,
    ncap: 4.0,
    url: prod3,
  },
  {
    _id: "p4",
    brand: "Suzuki",
    model: "Swift",
    price: "90000",
    categoryName: "hatchback",
    fueltype: "Cng",
    releaseYear: 1998,
    mileage: 25,
    preowned: true,
    ncap: 3.5,
    url: prod4,
  },
  {
    _id: "p5",
    brand: "Tata",
    model: "Tigor",
    price: "800000",
    categoryName: "sedan",
    fueltype: "Cng",
    releaseYear: 2012,
    mileage: 25,
    preowned: false,
    ncap: 2.5,
    url: prod5,
  },
  {
    _id: "p6",
    brand: "Hyundai",
    model: "Creta",
    price: "100000",
    categoryName: "suv",
    fueltype: "Diesel",
    releaseYear: 2012,
    mileage: 12,
    preowned: false,
    ncap: 3.2,
    url: prod16,
  },
  {
    _id: "p7",
    brand: "Suzuki",
    model: "Baleno",
    price: "700000",
    categoryName: "hatchback",
    fueltype: "Diesel",
    releaseYear: 2012,
    mileage: 17,
    preowned: false,
    ncap: 2.8,
    url: prod7,
  },
  {
    _id: "p8",
    brand: "Hyundai",
    model: "Aura",
    price: "70000",
    categoryName: "sedan",
    fueltype: "Diesel",
    releaseYear: 2001,
    mileage: 22,
    preowned: false,
    ncap: 1.9,
    url: prod8,
  },
  {
    _id: "p9",
    brand: "Tata",
    model: "Punch",
    price: "500000",
    categoryName: "suv",
    fueltype: "Diesel",
    releaseYear: 2019,
    mileage: 25,
    preowned: false,
    ncap: 3.8,
    url: prod9,
  },
  {
    _id: "p10",
    brand: "Suzuki",
    model: "Alto 800",
    price: "20000",
    categoryName: "hatchback",
    fueltype: "Petrol",
    releaseYear: 1980,
    mileage: 12,
    preowned: true,
    ncap: 4.8,
    url: prod10,
  },
  {
    _id: "p11",
    brand: "Honda",
    model: "Amaze",
    price: "1000000",
    categoryName: "sedan",
    fueltype: "Diesel",
    releaseYear: 2003,
    mileage: 16,
    preowned: false,
    ncap: 2.6,
    url: prod11,
  },
  {
    _id: "p12",
    brand: "Hyundai",
    model: "Venue",
    price: "100000",
    categoryName: "suv",
    fueltype: "Diesel",
    releaseYear: 2011,
    mileage: 7,
    preowned: true,
    ncap: 3.6,
    url: prod12,
  },
  {
    _id: "p13",
    brand: "Hyundai",
    model: "i20",
    price: "500000",
    categoryName: "hatchback",
    fueltype: "Cng",
    releaseYear: 2000,
    mileage: 27,
    preowned: true,
    ncap: 3.0,
    url: prod13,
  },
  {
    _id: "p14",
    brand: "Skoda",
    model: "Slavia",
    price: "1500000",
    categoryName: "sedan",
    fueltype: "Diesel",
    releaseYear: 2013,
    mileage: 16,
    preowned: false,
    ncap: 4.5,
    url: prod14,
  },
  {
    _id: "p15",
    brand: "Tata",
    model: "Harrier",
    price: "2200000",
    categoryName: "suv",
    fueltype: "Diesel",
    releaseYear: 2021,
    mileage: 20,
    preowned: false,
    ncap: 4.9,
    url: prod15,
  },
];
